from pathlib import Path

path = Path("petrolab/minerals/formulae.py")
text = path.read_text(encoding="utf-8")
old = '''    cats: dict[str, pd.Series] = {}\n    oxygen_moles = pd.Series(0.0, index=df.index, dtype=float)\n\n    # FeOt means total Fe expressed as FeO. It may stand in for FeO only when\n    # separate FeO is absent. FeOt plus a non-zero Fe2O3 column without FeO is\n    # chemically ambiguous and must not be silently double-counted.\n    if "FeOt" in df.columns and "FeO" not in df.columns and "Fe2O3" in df.columns:\n        measured_fe3 = pd.to_numeric(df["Fe2O3"], errors="coerce").fillna(0.0)\n        if (measured_fe3.abs() > 0).any():\n            raise ValueError(\n                "Одновременно заданы FeOt и Fe2O3 без отдельного FeO. "\n                "Нельзя однозначно разделить total Fe и измеренный Fe3+."\n            )\n\n    for oxide, spec in OXIDES.items():\n        if oxide not in allowed:\n            continue\n        source_column = oxide\n        if oxide == "FeO" and "FeO" not in df.columns and "FeOt" in df.columns:\n            source_column = "FeOt"\n        if source_column not in df.columns:\n            continue\n        moles_oxide = _num(df, source_column) / spec.molar_mass\n        oxygen_moles = oxygen_moles + moles_oxide * spec.n_oxygen\n        cat_moles = moles_oxide * spec.n_cation\n        cats[spec.cation] = cats.get(spec.cation, pd.Series(0.0, index=df.index)) + cat_moles\n'''
new = '''    cats: dict[str, pd.Series] = {}\n    oxygen_moles = pd.Series(0.0, index=df.index, dtype=float)\n\n    # FeO and FeOt can coexist as columns in historical merged datasets while being\n    # mutually exclusive row by row. Preserve NaN so the correct source can be chosen\n    # for every analysis instead of selecting one column globally.\n    feo_raw = (\n        pd.to_numeric(df["FeO"], errors="coerce")\n        if "FeO" in df.columns\n        else pd.Series(np.nan, index=df.index, dtype=float)\n    )\n    feot_raw = (\n        pd.to_numeric(df["FeOt"], errors="coerce")\n        if "FeOt" in df.columns\n        else pd.Series(np.nan, index=df.index, dtype=float)\n    )\n    fe3_raw = (\n        pd.to_numeric(df["Fe2O3"], errors="coerce")\n        if "Fe2O3" in df.columns\n        else pd.Series(np.nan, index=df.index, dtype=float)\n    )\n\n    both_feo_feot = feo_raw.notna() & feot_raw.notna()\n    if both_feo_feot.any():\n        rows = ", ".join(str(int(i) + 1) for i in df.index[both_feo_feot][:10])\n        raise ValueError(\n            "В одной или нескольких строках одновременно заданы FeO и FeOt "\n            f"(строки данных: {rows}). Нельзя выбрать источник Fe автоматически."\n        )\n\n    # FeOt is total Fe expressed as FeO. If a row also contains a separately supplied\n    # Fe2O3 value but no FeO, deriving Fe2+/Fe3+ would require an explicit method; do\n    # not double-count or infer it implicitly. Zero is still an explicit supplied value.\n    ambiguous_total_fe = feot_raw.notna() & feo_raw.isna() & fe3_raw.notna()\n    if ambiguous_total_fe.any():\n        rows = ", ".join(str(int(i) + 1) for i in df.index[ambiguous_total_fe][:10])\n        raise ValueError(\n            "Одновременно заданы FeOt и Fe2O3 без отдельного FeO "\n            f"(строки данных: {rows}). Нельзя однозначно разделить total Fe и Fe3+."\n        )\n\n    for oxide, spec in OXIDES.items():\n        if oxide not in allowed:\n            continue\n        if oxide == "FeO":\n            if "FeO" not in df.columns and "FeOt" not in df.columns:\n                continue\n            values = feo_raw.combine_first(feot_raw).fillna(0.0)\n        else:\n            if oxide not in df.columns:\n                continue\n            values = _num(df, oxide)\n        moles_oxide = values / spec.molar_mass\n        oxygen_moles = oxygen_moles + moles_oxide * spec.n_oxygen\n        cat_moles = moles_oxide * spec.n_cation\n        cats[spec.cation] = cats.get(spec.cation, pd.Series(0.0, index=df.index)) + cat_moles\n'''
if old not in text:
    raise SystemExit("mixed Fe target block not found; refusing non-deterministic patch")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
print("mixed Fe formula patch applied")
